### ISSUE TITLE
Instagram access attempt

### ISSUE THREAD

**Issue by artyomrs** [impshum/instagram-unfollow-bot#1]
I keep getting the message on instagram "unusual access attempt" and even if I mark it was me, it returns the same message when I try to run the script again.

```
Request return 400 error!
{'message': 'challenge_required', 'challenge': {'url': 'https://i.instagram.com/challenge/2055242638/VrFNBo7uQx/', 'api_path': '/challenge/2055242638/VrFNBo7uQx/', 'hide_webview_header': True, 'lock': True, 'logout': False, 'native_flow': True}, 'status': 'fail', 'error_type': 'checkpoint_challenge_required'}
[36m02/02/2020[0m
Traceback (most recent call last):
  File "run.py", line 93, in <module>
    main()
  File "run.py", line 89, in main
    instaspam(api, 10)
  File "run.py", line 39, in instaspam
    user_id = api.username_id
AttributeError: 'InstagramAPI' object has no attribute 'username_id'
```

**Comment by impshum** [comment]
Your error says ```message': 'challenge_required'``` and gives a link. I suggest you follow that.
